In [1]:
import pandas as pd
import numpy as np
import h5py
##import standard modules

import pynbody
from pynbody.analysis import profile
##import pynbody charachteristics

In [3]:
import sys
directory_path  = '/home/vadilloj/MAP2023/Vadillo-Justice-League-Code'
sys.path.append(directory_path)
##add my path to the sys.path to make it easier to add in and find documents.


from Runnable_Modules import Base as base, IonUtils as ions, TrackingUtils as tracking
from Runnable_Modules.IonUtils import HI_factor, OVI_factor
##import custom functions

In [7]:
##simulations is the pd data frame (in this case pre existing so imported from base) that stores the simulation charachteristics
##halo_chars is the pd data frame that stores the charachteristics of all halos within the simulations
simulations = base.get_chars('sims')
tracking.find_halo_keys(simulations)

()

In [8]:
tracked_filepath = "/home/christenc/Code/python/Justice_League_Code/Data/tracked_particles.hdf5"
HaloKeys = list(h5py.File(tracked_filepath).keys())
HaloKeys = sorted(HaloKeys, key=lambda x: int(x.split('_', 1)[1]))
HaloKeys = sorted(HaloKeys, key=lambda x: x.split('_', 1)[0])

In [9]:
Sandra2 = pd.read_hdf(tracked_filepath, key = 'h148_2')
akins = pd.DataFrame({'h148_2':Sandra2.iloc[0]})

In [10]:
for Halo in HaloKeys:
    data = pd.read_hdf(tracked_filepath, key = Halo)
    akins[Halo] = data.iloc[0]

In [11]:
newAkins = akins.loc[['satRvir','a', 'satRvir', 'hostRvir',
                      'sat_Xc', 'sat_Yc', 'sat_Zc', 
                      'sat_vx', 'sat_vy','sat_vz', 
                      'host_Xc', 'host_Yc', 'host_Zc',
                      'host_vx', 'host_vy', 'host_vz', 
                      'sat_Mstar', 'sat_Mgas',	'host_Mstar', 'host_Mgas',
                      'sat_r_half', 'sat_r_gas', 'host_r_half', 'host_r_gas']].transpose()

In [12]:
newAkins['x'] =newAkins['host_Xc']- newAkins['sat_Xc']
newAkins['y'] =newAkins['host_Yc']- newAkins['sat_Yc']
newAkins['z'] =newAkins['host_Zc']- newAkins['sat_Zc']

In [14]:
edge

NameError: name 'edge' is not defined

In [13]:
akins_path = directory_path + '/akins_charachteristics.csv'
newAkins.to_csv(akins_path)

In [24]:
newAkins

,satRvir,a,satRvir,hostRvir,sat_Xc,sat_Yc,sat_Zc,sat_vx,sat_vy,sat_vz,...,sat_Mgas,host_Mstar,host_Mgas,sat_r_half,sat_r_gas,host_r_half,host_r_gas,x,y,z
h148_2,86.629481,0.74721,86.629481,225.234444,18961.582757,18219.51383,18494.392925,-24.68,66.84,-120.56,...,5478930000.0,100328000000.0,99059300000.0,2.871309,7.411914,3.89124,20.11314,-63.334932,445.830432,-75.381265
h148_3,67.068286,0.615628,67.068286,179.248466,15683.917141,15626.639059,15446.666369,-140.15,-40.17,-60.09,...,3147140000.0,68991800000.0,81012200000.0,1.99717,6.560634,2.527426,18.54306,-129.636107,-248.878698,-225.645676
h148_4,59.477866,0.666686,59.477866,203.35213,16706.625732,16259.975149,16547.842747,-87.54,114.46,28.51,...,1060770000.0,83682400000.0,93413000000.0,2.426535,2.103175,3.446246,20.248449,138.875867,383.06441,-101.428056
h148_6,62.066456,0.720611,62.066456,219.545336,17850.082909,17923.795059,17480.187014,35.74,34.36,137.21,...,1247750000.0,95676200000.0,98455100000.0,2.31081,2.438029,3.97482,18.284842,373.805178,69.264402,288.889558
h148_7,50.762235,0.615628,50.762235,179.248466,15617.947712,15708.120715,15068.293474,36.47,-120.48,-64.42,...,398063000.0,68991800000.0,81012200000.0,0.914265,1.045421,2.527426,18.54306,-63.666678,-330.360354,152.727219
h148_10,36.708404,0.537186,36.708404,156.773659,13287.167792,13621.68409,13256.585139,182.6,-14.62,-61.85,...,514276000.0,55011400000.0,75310700000.0,0.77608,0.913015,2.402897,19.59562,288.426742,-214.19115,63.292371
h148_12,40.607272,0.589531,40.607272,171.710999,14630.158247,14821.05406,14516.26315,223.36,4.35,-61.07,...,167612000.0,64426500000.0,80507000000.0,0.873838,0.575378,2.468502,20.918,265.342808,-95.769195,75.117975
h148_23,28.49473,0.457383,28.49473,136.730159,11400.213909,11611.693603,11218.971589,144.42,-65.0,13.38,...,760219000.0,37444700000.0,69693200000.0,1.127396,2.312661,2.178251,19.856793,156.629744,-196.647482,157.660911
h148_27,29.534092,0.457383,29.534092,136.730159,11446.718567,11617.342138,11277.78734,140.75,-28.09,27.87,...,547285000.0,37444300000.0,69692800000.0,1.209758,1.577942,2.178251,19.856793,110.026179,-202.393712,98.747795
h148_34,28.512568,0.64174,28.512568,193.394946,16215.754449,15902.53655,15525.39902,72.86,-27.24,159.1,...,175525000.0,77549400000.0,89205700000.0,0.974752,1.165958,2.969249,18.113003,-2.435702,127.417611,323.060668
h148_38,27.339081,0.537186,27.339081,156.773659,13495.25987,13420.036426,13023.074668,119.45,-61.76,88.45,...,131591000.0,55011400000.0,75310700000.0,0.998875,1.211613,2.402897,19.59562,80.334664,-12.543485,296.802842
h148_55,28.176297,0.589531,28.176297,171.710999,14634.092145,14621.384099,14442.745538,34.6,86.03,59.16,...,201444000.0,64426500000.0,80507000000.0,0.471743,1.456896,2.468502,20.918,261.408911,103.900765,148.635588
h148_65,24.971696,0.457383,24.971696,136.730159,11512.912362,11649.568321,11372.883155,68.14,-95.14,-126.0,...,102649000.0,37444300000.0,69692800000.0,0.911734,0.832856,2.178251,19.856793,43.832384,-234.619895,3.65198
h148_249,22.945288,0.563402,22.945288,164.773772,14229.862642,14322.226498,13771.239189,128.99,-88.32,28.51,...,83784700.0,59910100000.0,78661300000.0,0.277275,0.48896,2.469965,18.844082,6.043777,-252.992641,187.359969
h148_251,19.280802,0.500057,19.280802,144.587569,12537.459056,12254.079052,12253.985062,107.97,114.55,29.09,...,67782300.0,47245600000.0,69070800000.0,0.711031,0.418394,2.323965,18.490257,101.124357,221.746674,154.898556
h148_282,14.305498,0.345009,14.305498,79.83588,8860.341813,8516.485499,8622.686129,-86.64,71.34,3.71,...,132874000.0,8211070000.0,33101500000.0,0.33528,0.472447,1.540719,14.784764,-190.680063,61.290726,-38.272041
h229_14,25.142043,0.571574,25.142043,138.23485,14399.536255,12404.402449,14003.031164,108.04,-214.98,-106.8,...,94279100.0,44185900000.0,37023800000.0,0.29549,0.987288,0.941319,17.903637,260.839072,-60.513418,-30.862966
h229_18,24.472262,0.457383,24.472262,111.157792,11784.508398,10201.712252,11249.711888,47.04,-62.3,-129.04,...,229000000.0,37790100000.0,29056800000.0,0.808171,1.288914,0.774364,10.009315,-117.272438,-74.140894,-37.216952
h229_20,23.233067,0.537186,23.233067,130.354071,13529.507278,11767.591101,13169.057802,117.86,-251.94,24.79,...,31015800.0,42584900000.0,34276800000.0,0.217492,0.521592,0.879432,14.849686,224.941671,-85.348979,-29.0054
h229_22,18.708525,0.457383,18.708525,111.157792,11739.588419,10318.013377,11187.374835,-53.94,-157.18,-99.74,...,34309900.0,37790100000.0,29056800000.0,0.538732,0.361022,0.774364,10.009315,-72.35246,-190.44202,25.120101
h229_49,24.29278,0.596056,24.29278,144.182311,15500.779704,12956.317204,14502.551975,-91.77,-151.57,66.35,...,45211900.0,45295400000.0,39028400000.0,0.637372,0.458615,0.979247,18.453055,-193.335428,-143.67576,61.535625
h242_8,39.90099,0.40001,39.90099,93.543032,10620.269999,11617.881548,10341.734518,-37.03,192.72,-12.88,...,2436760000.0,16127600000.0,32077700000.0,1.826689,6.909978,2.250656,10.261311,-179.368084,-71.090537,11.105175
h242_10,41.718964,0.40001,41.718964,93.543032,10568.467989,11636.973684,10222.202547,15.66,268.18,143.0,...,2973480000.0,16127600000.0,32077700000.0,1.197094,3.876896,2.250656,10.261311,-127.566074,-90.182674,130.637147
h242_21,24.163705,0.477562,24.163705,127.301641,12672.127402,13893.167531,12567.717337,30.15,149.91,-83.66,...,130275000.0,31312600000.0,50861100000.0,0.338769,0.557926,2.557724,10.941918,-130.851559,147.489723,-142.592538
h242_30,18.885372,0.416347,18.885372,98.837954,10653.6858,12067.237044,10793.155152,235.62,95.84,49.98,...,50093800.0,19012000000.0,33527500000.0,0.155885,0.709541,2.276877,14.073474,219.309075,5.212958,-12.190071
h242_38,31.979983,0.774023,31.979983,187.642548,20809.710649,24165.685317,20097.817103,219.66,131.02,85.79,...,26002800.0,57156700000.0,53635800000.0,0.357868,0.215888,2.117819,14.11842,196.404535,-141.914712,257.973348
h242_69,34.741666,0.596056,34.741666,152.529106,15846.269824,17907.264924,15854.873064,153.27,190.68,-46.9,...,165957000.0,46937100000.0,47310500000.0,0.911392,0.89123,2.449503,16.568967,51.058769,119.153394,-271.96564
h242_401,11.230704,0.35236,11.230704,76.821133,9048.931831,10063.579892,9072.94701,143.51,139.88,31.62,...,67564600.0,8144510000.0,25704500000.0,0.449472,0.815716,1.434836,13.432802,134.485005,-76.993179,21.122745
h329_7,37.692029,0.835306,37.692029,173.693943,22495.930578,17696.019564,21663.472278,26.08,-196.61,147.01,...,295412000.0,52420300000.0,20718800000.0,2.038042,0.91882,1.727132,4.673006,-136.172103,-132.204681,319.61845
h329_29,24.245599,0.615628,24.245599,137.2161,16330.996341,13425.959785,16239.296646,115.67,-208.08,-105.48,...,55643200.0,32675000000.0,27083700000.0,0.393142,0.543869,2.702715,12.364637,0.591894,29.138885,-231.654117
h329_117,16.243176,0.395399,16.243176,80.504072,10288.036804,8989.667765,10011.974325,57.81,-50.19,137.91,...,31641900.0,9588960000.0,23838200000.0,0.309584,0.445661,1.859005,12.146921,43.574834,66.44011,122.767307

In [47]:
path_mitsuru = directory_path +'/all-satellite-data.csv'

In [48]:
mitsuru = pd.read_csv(path_mitsuru, index_col = 0)

In [70]:
simulations.at['Elena', 'Halo keys']

[np.str_('h329_7'), np.str_('h329_29'), np.str_('h329_117')]

In [58]:
tracking.find_halo_keys(simulations)

()

In [19]:
Hchars = base.get_chars('halos')

In [51]:
for key in list(Hchars.index):
    x =  Hchars.at[key, 'x']-  HChars.at[key, 'x']
    y =  Hchars.at[key, 'y']-  HChars.at[key, 'y']
    z =  Hchars.at[key, 'z']-  HChars.at[key, 'z']
    
    print(f"{halo}-> x:{x}, y:{y}, z:{z}\\")

time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:-4626.37, y:-17341.69, z:-2252.5800000000004\
time-> x:-5234.4, y:-18228.710000000003, z:15786.06\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\
time-> x:0.0, y:0.0, z:0.0\

In [40]:
def get_chars(subsim,chars, key, trackedSubsim, IsSubsim = False):
    """
    gets the following charachteristics for the given subsim, and writes its charachteristics into the chars pd dictionary under key.
    'mass', 'mstar','mgas','Rvir',
    """
    
    chars.at[key, 'mass'] =np.sum(subsim['mass'])
    chars.at[key, 'mstar'] = np.sum(subsim.s['mass'])
    mass =  np.sum(subsim.g['mass'])
    OVI_mass =  np.sum(subsim.g['OVI_mass'])
    HI_mass =  np.sum(subsim.g['HI_mass'])
    chars.at[key, 'mgas'] = mass
    chars.at[key, 'OVI_mass'] = OVI_mass
    chars.at[key, 'HI_mass'] = HI_mass
    
    if IsSubsim:
        chars.at[key, 'host_mass_frac'] = (np.sum(trackedSubsim.g['mass'])/np.sum(h1.g['mass']))
        chars.at[key, 'host_HI_frac']  = (np.sum(trackedSubsim.g['HI_mass'])/np.sum(h1.g['HI_mass']))
        chars.at[key, 'host_OVI_frac']  = (np.sum(trackedSubsim.g['OVI_mass'])/np.sum(h1.g['OVI_mass']))
    else:
        chars.at[key, 'sat_mass_frac'] =  (np.sum(trackedSubsim.g['mass'])/chars['mass'][key])
        chars.at[key, 'sat_HI_frac']  = (np.sum(trackedSubsim.g['HI_mass'])/chars['HI_mass'][key])
        chars.at[key, 'sat_OVI_frac']  = (np.sum(trackedSubsim.g['OVI_mass'])/chars['OVI_mass'][key])

        chars.at[key, 'Rvir'] = np.max(subsim.g['r'])

In [41]:
def get_halo_chars(subsim, chars, key,tracked_subsim):
    warnings.filterwarnings("error")
    try:
        pos = pynbody.analysis.halo.center(subsim, return_cen = True).tolist() # recenters
    except RuntimeWarning:
        pos = tracked_subsim.mean_by_mass('pos')
    warnings.resetwarnings()
    chars.at[key, 'x'] = round(pos[0], 2)
    chars.at[key, 'y'] = round(pos[1], 2)
    chars.at[key, 'z'] = round(pos[2], 2)
    chars.at[key, 'Hdist'] = round(np.sqrt(pos[0]**2+pos[1]**2+pos[2]**2), 2)
    

    with pynbody.analysis.center(subsim):
        chars.at[key, 'Rvir'] = np.max(subsim['r'])
    get_chars(subsim,chars, key, trackedSubsim, IsSubsim = True)
        
    chars.at[key, 'M_inhalo'] =  chars['mgas'][key]/(np.sum(trackedSubsim.g['mass']))
    chars.at[key, 'HI_inhalo']  = chars['HI_mass'][key]/(np.sum(trackedSubsim.g['HI_mass']))
    chars.at[key, 'OVI_inhalo']  = chars['OVI_mass'][key]/(np.sum(trackedSubsim.g['OVI_mass']))

In [29]:
akins_path = '/home/vadilloj/MAP2023/Vadillo-Justice-League-Code/akins_charachteristics.csv'
import importlib
importlib.reload(base)
simulations = base.get_chars('sims')
tracking.find_halo_keys(simulations)
simulations = base.FormatDF(simulations)
akins = pd.read_csv(akins_path, index_col = 0)
akins = base.FormatDF(akins)

In [30]:
akins

,satRvir,a,satRvir.1,hostRvir,sat_Xc,sat_Yc,sat_Zc,sat_vx,sat_vy,sat_vz,...,sat_Mgas,host_Mstar,host_Mgas,sat_r_half,sat_r_gas,host_r_half,host_r_gas,x,y,z
h148_2,86.629481,0.747210,86.629481,225.234444,18961.582757,18219.513830,18494.392925,-24.68,66.84,-120.56,...,5.478930e+09,1.003280e+11,9.905930e+10,2.871309,7.411914,3.891240,20.113140,-63.334932,445.830432,-75.381265
h148_3,67.068286,0.615628,67.068286,179.248466,15683.917141,15626.639059,15446.666369,-140.15,-40.17,-60.09,...,3.147140e+09,6.899180e+10,8.101220e+10,1.997170,6.560634,2.527426,18.543060,-129.636107,-248.878698,-225.645676
h148_4,59.477866,0.666686,59.477866,203.352130,16706.625732,16259.975149,16547.842747,-87.54,114.46,28.51,...,1.060770e+09,8.368240e+10,9.341300e+10,2.426535,2.103175,3.446246,20.248449,138.875867,383.064410,-101.428056
h148_6,62.066456,0.720611,62.066456,219.545336,17850.082909,17923.795059,17480.187014,35.74,34.36,137.21,...,1.247750e+09,9.567620e+10,9.845510e+10,2.310810,2.438029,3.974820,18.284842,373.805178,69.264402,288.889558
h148_7,50.762235,0.615628,50.762235,179.248466,15617.947712,15708.120715,15068.293474,36.47,-120.48,-64.42,...,3.980630e+08,6.899180e+10,8.101220e+10,0.914265,1.045421,2.527426,18.543060,-63.666678,-330.360354,152.727219
h148_10,36.708404,0.537186,36.708404,156.773659,13287.167792,13621.684090,13256.585139,182.60,-14.62,-61.85,...,5.142760e+08,5.501140e+10,7.531070e+10,0.776080,0.913015,2.402897,19.595620,288.426742,-214.191150,63.292371
h148_12,40.607272,0.589531,40.607272,171.710999,14630.158247,14821.054060,14516.263150,223.36,4.35,-61.07,...,1.676120e+08,6.442650e+10,8.050700e+10,0.873838,0.575378,2.468502,20.918000,265.342808,-95.769195,75.117975
h148_23,28.494730,0.457383,28.494730,136.730159,11400.213909,11611.693603,11218.971589,144.42,-65.00,13.38,...,7.602190e+08,3.744470e+10,6.969320e+10,1.127396,2.312661,2.178251,19.856793,156.629744,-196.647482,157.660911
h148_27,29.534092,0.457383,29.534092,136.730159,11446.718567,11617.342138,11277.787340,140.75,-28.09,27.87,...,5.472850e+08,3.744430e+10,6.969280e+10,1.209758,1.577942,2.178251,19.856793,110.026179,-202.393712,98.747795
h148_34,28.512568,0.641740,28.512568,193.394946,16215.754449,15902.536550,15525.399020,72.86,-27.24,159.10,...,1.755250e+08,7.754940e+10,8.920570e+10,0.974752,1.165958,2.969249,18.113003,-2.435702,127.417611,323.060668
h148_38,27.339081,0.537186,27.339081,156.773659,13495.259870,13420.036426,13023.074668,119.45,-61.76,88.45,...,1.315910e+08,5.501140e+10,7.531070e+10,0.998875,1.211613,2.402897,19.595620,80.334664,-12.543485,296.802842
h148_55,28.176297,0.589531,28.176297,171.710999,14634.092145,14621.384099,14442.745538,34.60,86.03,59.16,...,2.014440e+08,6.442650e+10,8.050700e+10,0.471743,1.456896,2.468502,20.918000,261.408911,103.900765,148.635588
h148_65,24.971696,0.457383,24.971696,136.730159,11512.912362,11649.568321,11372.883155,68.14,-95.14,-126.00,...,1.026490e+08,3.744430e+10,6.969280e+10,0.911734,0.832856,2.178251,19.856793,43.832384,-234.619895,3.651980
h148_249,22.945288,0.563402,22.945288,164.773772,14229.862642,14322.226498,13771.239189,128.99,-88.32,28.51,...,8.378470e+07,5.991010e+10,7.866130e+10,0.277275,0.488960,2.469965,18.844082,6.043777,-252.992641,187.359969
h148_251,19.280802,0.500057,19.280802,144.587569,12537.459056,12254.079052,12253.985062,107.97,114.55,29.09,...,6.778230e+07,4.724560e+10,6.907080e+10,0.711031,0.418394,2.323965,18.490257,101.124357,221.746674,154.898556
h148_282,14.305498,0.345009,14.305498,79.835880,8860.341813,8516.485499,8622.686129,-86.64,71.34,3.71,...,1.328740e+08,8.211070e+09,3.310150e+10,0.335280,0.472447,1.540719,14.784764,-190.680063,61.290726,-38.272041
h229_14,25.142043,0.571574,25.142043,138.234850,14399.536255,12404.402449,14003.031164,108.04,-214.98,-106.80,...,9.427910e+07,4.418590e+10,3.702380e+10,0.295490,0.987288,0.941319,17.903637,260.839072,-60.513418,-30.862966
h229_18,24.472262,0.457383,24.472262,111.157792,11784.508398,10201.712252,11249.711888,47.04,-62.30,-129.04,...,2.290000e+08,3.779010e+10,2.905680e+10,0.808171,1.288914,0.774364,10.009315,-117.272438,-74.140894,-37.216952
h229_20,23.233067,0.537186,23.233067,130.354071,13529.507278,11767.591101,13169.057802,117.86,-251.94,24.79,...,3.101580e+07,4.258490e+10,3.427680e+10,0.217492,0.521592,0.879432,14.849686,224.941671,-85.348979,-29.005400
h229_22,18.708525,0.457383,18.708525,111.157792,11739.588419,10318.013377,11187.374835,-53.94,-157.18,-99.74,...,3.430990e+07,3.779010e+10,2.905680e+10,0.538732,0.361022,0.774364,10.009315,-72.352460,-190.442020,25.120101
h229_49,24.292780,0.596056,24.292780,144.182311,15500.779704,12956.317204,14502.551975,-91.77,-151.57,66.35,...,4.521190e+07,4.529540e+10,3.902840e+10,0.637372,0.458615,0.979247,18.453055,-193.335428,-143.675760,61.535625
h242_8,39.900990,0.400010,39.900990,93.543032,10620.269999,11617.881548,10341.734518,-37.03,192.72,-12.88,...,2.436760e+09,1.612760e+10,3.207770e+10,1.826689,6.909978,2.250656,10.261311,-179.368084,-71.090537,11.105175
h242_10,41.718964,0.400010,41.718964,93.543032,10568.467989,11636.973684,10222.202547,15.66,268.18,143.00,...,2.973480e+09,1.612760e+10,3.207770e+10,1.197094,3.876896,2.250656,10.261311,-127.566074,-90.182674,130.637147
h242_21,24.163705,0.477562,24.163705,127.301641,12672.127402,13893.167531,12567.717337,30.15,149.91,-83.66,...,1.302750e+08,3.131260e+10,5.086110e+10,0.338769,0.557926,2.557724,10.941918,-130.851559,147.489723,-142.592538
h242_30,18.885372,0.416347,18.885372,98.837954,10653.685800,12067.237044,10793.155152,235.62,95.84,49.98,...,5.009380e+07,1.901200e+10,3.352750e+10,0.155885,0.709541,2.276877,14.073474,219.309075,5.212958,-12.190071
h242_38,31.979983,0.774023,31.979983,187.642548,20809.710649,24165.685317,20097.817103,219.66,131.02,85.79,...,2.600280e+07,5.715670e+10,5.363580e+10,0.357868,0.215888,2.117819,14.118420,196.404535,-141.914712,257.973348
h242_69,34.741666,0.596056,34.741666,152.529106,15846.269824,17907.264924,15854.873064,153.27,190.68,-46.90,...,1.659570e+08,4.693710e+10,4.731050e+10,0.911392,0.891230,2.449503,16.568967,51.058769,119.153394,-271.965640
h242_401,11.230704,0.352360,11.230704,76.821133,9048.931831,10063.579892,9072.947010,143.51,139.88,31.62,...,6.756460e+07,8.144510e+09,2.570450e+10,0.449472,0.815716,1.434836,13.432802,134.485005,-76.993179,21.122745
h329_7,37.692029,0.835306,37.692029,173.693943,22495.930578,17696.019564,21663.472278,26.08,-196.61,147.01,...,2.954120e+08,5.242030e+10,2.071880e+10,2.038042,0.918820,1.727132,4.673006,-136.172103,-132.204681,319.618450
h329_29,24.245599,0.615628,24.245599,137.216100,16330.996341,13425.959785,16239.296646,115.67,-208.08,-105.48,...,5.564320e+07,3.267500e+10,2.708370e+10,0.393142,0.543869,2.702715,12.364637,0.591894,29.138885,-231.654117
h329_117,16.243176,0.395399,16.243176,80.504072,10288.036804,8989.667765,10011.974325,57.81,-50.19,137.91,...,3.164190e+07,9.588960e+09,2.383820e+10,0.309584,0.445661,1.859005,12.146921,43.574834,66.440110,122.767307

In [43]:
HChars = base.get_chars('halos')

,time,mstar,mgas,mass,Rvir,x,y,z,Hdist,sfr,t_infall,HI_mass,OVI_mass,host_mass_frac,host_HI_frac,host_OVI_frac,M_inhalo,HI_inhalo,OVI_inhalo
key,,,,,,,,,,,,,,,,,,,
h148_2,13.800797,2.268773e+09,8.252345e+09,9.575866e+10,95.462198,-59.60,-162.55,78.24,189.99,0.476290,NaN,3.166450e+09,2.951845e+04,0.069372,0.224568,0.045517,0.778978,9.970521e-01,2.485345e-01
h148_3,NaN,1.502171e+09,2.975036e+09,4.697010e+10,76.483584,236.62,48.30,114.24,267.16,NaN,NaN,1.027898e+09,1.106206e+04,0.018130,0.040023,0.018883,1.074575,1.816059e+00,2.245034e-01
h148_4,13.800797,4.317847e+08,9.706413e+08,3.248971e+10,67.335904,65.83,-236.64,6.32,245.71,0.025735,NaN,3.577707e+08,1.630198e+03,0.009046,0.025346,0.007483,0.702660,9.981530e-01,8.349161e-02
h148_6,13.800797,3.315968e+08,1.010160e+09,2.869601e+10,64.716224,280.59,-104.37,-129.01,325.99,0.037392,NaN,3.569206e+08,1.589113e+03,0.004255,0.000749,0.003830,1.554449,3.371363e+01,1.590088e-01
h148_10,13.800797,1.353274e+08,1.139460e+09,1.055766e+10,46.469675,-24.02,-133.76,-5.92,136.03,0.022669,NaN,4.378722e+08,1.161519e+02,0.013847,0.035053,0.006264,0.538852,8.833165e-01,7.106595e-03
h148_12,13.800797,1.043767e+08,7.503453e+06,9.071870e+09,43.979036,42.64,281.50,-2.79,284.73,0.000137,NaN,3.043587e+05,8.613388e+01,0.000929,0.001414,0.001445,0.052891,1.522334e-02,2.284602e-02
h148_27,13.800797,8.415728e+07,1.026774e+08,3.249352e+09,31.367917,237.78,147.66,-94.98,295.57,0.000535,NaN,2.159628e+07,2.503571e+01,0.005458,0.006517,0.008144,0.123195,2.343291e-01,1.178148e-03
h148_34,13.800797,5.759679e+06,5.869542e+07,2.628660e+09,29.130301,-296.06,-315.65,-241.34,495.51,0.000000,NaN,6.332316e+06,1.688300e+02,0.000690,0.000282,0.000417,0.556970,1.586624e+00,1.552734e-01
h148_38,13.800797,1.374093e+07,0.000000e+00,1.883522e+09,26.060232,2.87,48.18,-181.80,188.10,0.000000,NaN,0.000000e+00,0.000000e+00,0.000981,0.000951,0.001479,0.000000,0.000000e+00,0.000000e+00
h148_55,13.800797,2.822993e+06,5.263210e+06,1.361924e+09,23.525588,-71.52,14.26,33.44,80.23,0.000000,NaN,1.317506e+06,0.000000e+00,0.001582,0.001107,0.002223,0.021787,8.419661e-02,0.000000e+00
h148_65,13.800797,3.001293e+07,0.000000e+00,8.996108e+08,20.341280,-33.33,-76.81,83.05,117.92,0.000000,NaN,0.000000e+00,0.000000e+00,0.000499,0.000794,0.000972,0.000000,0.000000e+00,0.000000e+00
h148_251,13.800797,2.149496e+06,0.000000e+00,1.815621e+08,11.952184,197.98,6.38,-219.66,295.78,0.000000,NaN,0.000000e+00,0.000000e+00,0.000280,0.000673,0.000846,0.000000,0.000000e+00,0.000000e+00
h148_249,13.800797,2.063790e+06,0.000000e+00,1.861386e+08,12.084551,29.14,180.63,10.97,183.29,0.000000,NaN,0.000000e+00,0.000000e+00,0.000692,0.001447,0.001075,0.000000,0.000000e+00,0.000000e+00
h148_282,13.800797,3.984286e+06,0.000000e+00,1.495318e+08,11.235650,112.71,128.88,60.19,181.49,0.000000,NaN,0.000000e+00,0.000000e+00,0.000207,0.000477,0.000522,0.000000,0.000000e+00,0.000000e+00
h229_14,13.800797,3.338275e+06,2.703543e+07,2.403511e+09,28.258460,257.66,301.63,-53.13,400.24,0.000000,NaN,2.421080e+06,9.500366e+01,0.000651,0.000245,0.000971,0.539821,5.312464e-01,6.970784e-02
h229_18,13.800797,7.714878e+07,0.000000e+00,1.509991e+09,24.209733,20.23,43.32,128.95,137.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.003526,0.005233,0.004190,0.000000,0.000000e+00,0.000000e+00
h229_20,13.800797,8.610682e+05,6.519790e+05,2.025912e+09,26.697664,-7.16,200.96,-183.88,272.48,0.000000,NaN,6.455090e+02,1.334474e+00,0.000332,0.000075,0.000387,0.025534,4.622822e-04,2.459367e-03
h229_22,13.800797,4.786508e+06,0.000000e+00,1.551642e+09,24.447656,-27.96,-38.13,-219.32,224.36,0.000000,NaN,0.000000e+00,0.000000e+00,0.000404,0.000250,0.000646,0.000000,0.000000e+00,0.000000e+00
h229_49,13.800797,6.790767e+06,0.000000e+00,7.641975e+08,19.306726,7.39,-109.24,-11.25,110.06,0.000000,NaN,0.000000e+00,0.000000e+00,0.000750,0.000637,0.000524,0.000000,0.000000e+00,0.000000e+00
h242_8,13.800797,0.000000e+00,2.916159e+05,5.397006e+12,2524.255371,2618.05,-5147.36,-1756.73,6036.19,0.034354,NaN,1.008922e-02,2.359862e-10,0.042365,0.053616,0.033327,0.000075,8.700136e-12,6.126794e-15
h242_10,13.800797,2.477138e+08,2.276692e+09,1.211725e+11,14901.587088,578.01,-945.70,-335.24,1157.94,0.009396,NaN,2.710142e+08,4.157601e+04,0.046579,0.056213,0.045138,0.533666,2.229021e-01,7.969718e-01
h242_21,13.800797,0.000000e+00,0.000000e+00,1.139806e+12,29062.027289,-4040.41,2166.01,6379.09,7855.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.002215,0.000304,0.004424,0.000000,0.000000e+00,0.000000e+00
h242_30,13.800797,5.322599e+07,1.453714e+09,7.091480e+09,24867.343522,-20494.08,-13965.20,-1154.72,24826.75,0.000000,NaN,7.356529e+08,6.335230e-04,0.000724,0.000923,0.000627,21.916692,3.685118e+01,8.742064e-07
h242_38,13.800797,0.000000e+00,0.000000e+00,7.776950e+09,17343.015297,-4648.07,-17372.41,-2285.26,18128.09,0.000000,NaN,0.000000e+00,0.000000e+00,0.000466,0.000075,0.000423,0.000000,0.000000e+00,0.000000e+00
h242_69,13.800797,1.149230e+07,4.381391e+07,9.322223e+09,23912.836453,-5233.07,-18227.97,15780.35,24671.10,0.000000,NaN,6.489503e+06,9.188295e+02,0.002812,0.002372,0.002153,0.170138,1.264801e-01,3.691732e-01
h242_401,13.800797,0.000000e+00,0.000000e+00,8.967824e+10,32993.649324,2363.01,-11798.80,2783.86,12350.93,0.000000,NaN,0.000000e+00,0.000000e+00,0.000509,0.000661,0.000422,0.000000,0.000000e+00,0.000000e+00
h329_7,13.800797,2.747402e+07,2.476791e+08,5.129210e+09,32.738173,53.53,-33.41,15.58,64.99,0.001193,NaN,6.756492e+07,4.063190e-02,0.017682,0.111979,0.002594,0.524004,9.712702e-01,2.060643e-05
h329_29,13.800797,1.491121e+06,0.000000e+00,1.403478e+09,23.658594,-240.56,-506.82,113.85,572.45,0.000000,NaN,0.000000e+00,0.000000e+00,0.001573,0.001954,0.001923,0.000000,0.000000e+00,0.000000e+00
h329_117,13.800797,3.084173e+06,0.000000e+00,2.398850e+08,13.075619,52.26,59.03,-81.65,113.50,0.000000,NaN,0.000000e+00,0.000000e+00,0.000062,0.000077,0.000078,0.000000,0.000000e+00,0.000000e+00
h148_7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
HChars.loc['h148_7'] = np.nan
HChars.loc['h148_23'] = np.nan

In [45]:
import warnings
filenames  = [ 'Sandra', 'Sonia', 'Ruth', 'Elena']
for filename in filenames:
    simulations.at[filename, 'nSats'] = len(simulations['Halo keys'][filename])
    s, h1, h = base.load_in_sim(filename, return_h = True)
    print("loaded in halo")
    ions.calculate_gas_mass(s)
    print("loaded in sims")
    subsims = tracking.find_halo_particles(h1, filename)
    get_chars(h1, simulations, filename, subsims['halos'])
    print(filename + " big chars done" )
    for key in simulations['Halo keys'][filename]:
        if key in list(HChars.index):
            halonum = (key.split('_')[1])
            halokey ="h"+halonum #string denoting the halo of origin
            trackedSubsim = subsims[halokey]
            
            get_halo_chars(h[int(halonum)], HChars, key,trackedSubsim)
    print(filename + " all done" )

loaded in halo
loaded in sims
Sandra big chars done

/home/vadilloj/anaconda3/envs/conda-env-py311/lib/python3.11/site-packages/pynbody/halo/__init__.py:274: RuntimeWarning: Accessing multiple halos may be more efficient if you call load_all() on the halo catalogue
  warnings.warn("Accessing multiple halos may be more efficient if you call load_all() on the "

Sandra all done

pynbody.halo : Unable to load AHF substructure file; continuing without. To expose the underlying problem as an exception, pass ignore_missing_substructure=False to the AHFCatalogue constructor

loaded in halo
loaded in sims
Sonia big chars done

/home/vadilloj/anaconda3/envs/conda-env-py311/lib/python3.11/site-packages/pynbody/halo/__init__.py:274: RuntimeWarning: Accessing multiple halos may be more efficient if you call load_all() on the halo catalogue
  warnings.warn("Accessing multiple halos may be more efficient if you call load_all() on the "
/home/vadilloj/anaconda3/envs/conda-env-py311/lib/python3.11/site-packages/pynbody/analysis/halo.py:100: RuntimeWarning: Final sphere is empty; cannot return a velocity. This probably implies something is wrong with the position centre too.
  warnings.warn("Final sphere is empty; cannot return a velocity. This probably implies something is "
/home/vadilloj/anaconda3/envs/conda-env-py311/lib/python3.11/site-packages/pynbody/analysis/halo.py:100: RuntimeWarning: Final sphere is empty; cannot return a velocity. This probably implies something is wrong with the position centre too.
  warnings.warn("Final sphere is empty; cannot return a velocity. This probably implies something is "

Sonia all done
loaded in halo
loaded in sims
Ruth big chars done

/home/vadilloj/anaconda3/envs/conda-env-py311/lib/python3.11/site-packages/pynbody/halo/__init__.py:274: RuntimeWarning: Accessing multiple halos may be more efficient if you call load_all() on the halo catalogue
  warnings.warn("Accessing multiple halos may be more efficient if you call load_all() on the "

Ruth all done
loaded in halo
loaded in sims
Elena big chars done
Elena all done

In [52]:

HChars.to_csv(HChars_path)

In [48]:
HChars_path = '/home/vadilloj/MAP2023/Vadillo-Justice-League-Code/All_halo_charachteristics.csv'
Hchars = pd.read_csv(HChars_path, index_col = 0)

In [46]:
HChars

,time,mstar,mgas,mass,Rvir,x,y,z,Hdist,sfr,t_infall,HI_mass,OVI_mass,host_mass_frac,host_HI_frac,host_OVI_frac,M_inhalo,HI_inhalo,OVI_inhalo
key,,,,,,,,,,,,,,,,,,,
h148_2,13.800797,2.268773e+09,8.252345e+09,9.575866e+10,95.462198,-59.60,-162.55,78.24,189.99,0.476290,NaN,3.166450e+09,2.951845e+04,0.069372,0.224568,0.045517,0.778978,9.970521e-01,2.485345e-01
h148_3,NaN,1.502171e+09,2.975036e+09,4.697010e+10,76.483584,236.62,48.30,114.24,267.16,NaN,NaN,1.027898e+09,1.106206e+04,0.018130,0.040023,0.018883,1.074575,1.816059e+00,2.245034e-01
h148_4,13.800797,4.317847e+08,9.706413e+08,3.248971e+10,67.335904,65.83,-236.64,6.32,245.71,0.025735,NaN,3.577707e+08,1.630198e+03,0.009046,0.025346,0.007483,0.702660,9.981530e-01,8.349161e-02
h148_6,13.800797,3.315968e+08,1.010160e+09,2.869601e+10,64.716224,280.59,-104.37,-129.01,325.99,0.037392,NaN,3.569206e+08,1.589113e+03,0.004255,0.000749,0.003830,1.554449,3.371363e+01,1.590088e-01
h148_10,13.800797,1.353274e+08,1.139460e+09,1.055766e+10,46.469675,-24.02,-133.76,-5.92,136.03,0.022669,NaN,4.378722e+08,1.161519e+02,0.013847,0.035053,0.006264,0.538852,8.833165e-01,7.106595e-03
h148_12,13.800797,1.043767e+08,7.503453e+06,9.071870e+09,43.979036,42.64,281.50,-2.79,284.73,0.000137,NaN,3.043587e+05,8.613388e+01,0.000929,0.001414,0.001445,0.052891,1.522334e-02,2.284602e-02
h148_27,13.800797,8.415728e+07,1.026774e+08,3.249352e+09,31.367917,237.78,147.66,-94.98,295.57,0.000535,NaN,2.159628e+07,2.503571e+01,0.005458,0.006517,0.008144,0.123195,2.343291e-01,1.178148e-03
h148_34,13.800797,5.759679e+06,5.869542e+07,2.628660e+09,29.130301,-296.06,-315.65,-241.34,495.51,0.000000,NaN,6.332316e+06,1.688300e+02,0.000690,0.000282,0.000417,0.556970,1.586624e+00,1.552734e-01
h148_38,13.800797,1.374093e+07,0.000000e+00,1.883522e+09,26.060232,2.87,48.18,-181.80,188.10,0.000000,NaN,0.000000e+00,0.000000e+00,0.000981,0.000951,0.001479,0.000000,0.000000e+00,0.000000e+00
h148_55,13.800797,2.822993e+06,5.263210e+06,1.361924e+09,23.525588,-71.52,14.26,33.44,80.23,0.000000,NaN,1.317506e+06,0.000000e+00,0.001582,0.001107,0.002223,0.021787,8.419661e-02,0.000000e+00
h148_65,13.800797,3.001293e+07,0.000000e+00,8.996108e+08,20.341280,-33.33,-76.81,83.05,117.92,0.000000,NaN,0.000000e+00,0.000000e+00,0.000499,0.000794,0.000972,0.000000,0.000000e+00,0.000000e+00
h148_251,13.800797,2.149496e+06,0.000000e+00,1.815621e+08,11.952184,197.98,6.38,-219.66,295.78,0.000000,NaN,0.000000e+00,0.000000e+00,0.000280,0.000673,0.000846,0.000000,0.000000e+00,0.000000e+00
h148_249,13.800797,2.063790e+06,0.000000e+00,1.861386e+08,12.084551,29.14,180.63,10.97,183.29,0.000000,NaN,0.000000e+00,0.000000e+00,0.000692,0.001447,0.001075,0.000000,0.000000e+00,0.000000e+00
h148_282,13.800797,3.984286e+06,0.000000e+00,1.495318e+08,11.235650,112.71,128.88,60.19,181.49,0.000000,NaN,0.000000e+00,0.000000e+00,0.000207,0.000477,0.000522,0.000000,0.000000e+00,0.000000e+00
h229_14,13.800797,3.338275e+06,2.703543e+07,2.403511e+09,28.258460,257.66,301.63,-53.13,400.24,0.000000,NaN,2.421080e+06,9.500366e+01,0.000651,0.000245,0.000971,0.539821,5.312464e-01,6.970784e-02
h229_18,13.800797,7.714878e+07,0.000000e+00,1.509991e+09,24.209733,20.23,43.32,128.95,137.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.003526,0.005233,0.004190,0.000000,0.000000e+00,0.000000e+00
h229_20,13.800797,8.610682e+05,6.519790e+05,2.025912e+09,26.697664,-7.16,200.96,-183.88,272.48,0.000000,NaN,6.455090e+02,1.334474e+00,0.000332,0.000075,0.000387,0.025534,4.622822e-04,2.459367e-03
h229_22,13.800797,4.786508e+06,0.000000e+00,1.551642e+09,24.447656,-27.96,-38.13,-219.32,224.36,0.000000,NaN,0.000000e+00,0.000000e+00,0.000404,0.000250,0.000646,0.000000,0.000000e+00,0.000000e+00
h229_49,13.800797,6.790767e+06,0.000000e+00,7.641975e+08,19.306726,7.39,-109.24,-11.25,110.06,0.000000,NaN,0.000000e+00,0.000000e+00,0.000750,0.000637,0.000524,0.000000,0.000000e+00,0.000000e+00
h242_8,13.800797,0.000000e+00,2.916159e+05,5.397006e+12,2524.255371,2618.05,-5147.36,-1756.73,6036.19,0.034354,NaN,1.008922e-02,2.359862e-10,0.042365,0.053616,0.033327,0.000075,8.700136e-12,6.126794e-15
h242_10,13.800797,2.477138e+08,2.276692e+09,1.211725e+11,14901.587088,578.01,-945.70,-335.24,1157.94,0.009396,NaN,2.710142e+08,4.157601e+04,0.046579,0.056213,0.045138,0.533666,2.229021e-01,7.969718e-01
h242_21,13.800797,0.000000e+00,0.000000e+00,1.139806e+12,29062.027289,-4040.41,2166.01,6379.09,7855.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.002215,0.000304,0.004424,0.000000,0.000000e+00,0.000000e+00
h242_30,13.800797,5.322599e+07,1.453714e+09,7.091480e+09,24867.343522,-20494.08,-13965.20,-1154.72,24826.75,0.000000,NaN,7.356529e+08,6.335230e-04,0.000724,0.000923,0.000627,21.916692,3.685118e+01,8.742064e-07
h242_38,13.800797,0.000000e+00,0.000000e+00,7.776950e+09,17343.014157,-21.70,-30.72,-32.68,49.82,0.000000,NaN,0.000000e+00,0.000000e+00,0.000466,0.000075,0.000423,0.000000,0.000000e+00,0.000000e+00
h242_69,13.800797,1.149230e+07,4.381391e+07,9.322223e+09,23912.839075,1.33,0.74,-5.71,5.91,0.000000,NaN,6.489503e+06,9.188295e+02,0.002812,0.002372,0.002153,0.170138,1.264801e-01,3.691732e-01
h242_401,13.800797,0.000000e+00,0.000000e+00,8.967824e+10,32993.649324,2363.01,-11798.80,2783.86,12350.93,0.000000,NaN,0.000000e+00,0.000000e+00,0.000509,0.000661,0.000422,0.000000,0.000000e+00,0.000000e+00
h329_7,13.800797,2.747402e+07,2.476791e+08,5.129210e+09,32.738173,53.53,-33.41,15.58,64.99,0.001193,NaN,6.756492e+07,4.063190e-02,0.017682,0.111979,0.002594,0.524004,9.712702e-01,2.060643e-05
h329_29,13.800797,1.491121e+06,0.000000e+00,1.403478e+09,23.658594,-240.56,-506.82,113.85,572.45,0.000000,NaN,0.000000e+00,0.000000e+00,0.001573,0.001954,0.001923,0.000000,0.000000e+00,0.000000e+00
h329_117,13.800797,3.084173e+06,0.000000e+00,2.398850e+08,13.075619,52.26,59.03,-81.65,113.50,0.000000,NaN,0.000000e+00,0.000000e+00,0.000062,0.000077,0.000078,0.000000,0.000000e+00,0.000000e+00
h148_7,NaN,2.359537e+08,1.596514e+08,1.561130e+10,52.752688,-112.68,93.32,-317.38,349.48,NaN,NaN,3.420422e+07,8.692021e+02,0.001909,0.001204,0.002084,0.547776,2.008183e+00,1.598090e-01
h148_23,NaN,1.004013e+08,3.775411e+08,3.333412e+09,32.018841,180.87,90.67,-160.70,258.38,NaN,NaN,9.235380e+07,2.002626e+01,0.009280,0.017120,0.012794,0.266422,3.814592e-01,5.998571e-04

In [50]:
Hchars

,time,mstar,mgas,mass,Rvir,x,y,z,Hdist,sfr,t_infall,HI_mass,OVI_mass,host_mass_frac,host_HI_frac,host_OVI_frac,M_inhalo,HI_inhalo,OVI_inhalo
key,,,,,,,,,,,,,,,,,,,
h148_2,13.800797,2.268773e+09,8.252345e+09,9.575866e+10,95.462198,-59.60,-162.55,78.24,189.99,0.476290,NaN,3.166450e+09,2.951845e+04,0.069372,0.224568,0.045517,0.778978,9.970521e-01,2.485345e-01
h148_3,NaN,1.502171e+09,2.975036e+09,4.697010e+10,76.483584,236.62,48.30,114.24,267.16,NaN,NaN,1.027898e+09,1.106206e+04,0.018130,0.040023,0.018883,1.074575,1.816059e+00,2.245034e-01
h148_4,13.800797,4.317847e+08,9.706413e+08,3.248971e+10,67.335904,65.83,-236.64,6.32,245.71,0.025735,NaN,3.577707e+08,1.630198e+03,0.009046,0.025346,0.007483,0.702660,9.981530e-01,8.349161e-02
h148_6,13.800797,3.315968e+08,1.010160e+09,2.869601e+10,64.716224,280.59,-104.37,-129.01,325.99,0.037392,NaN,3.569206e+08,1.589113e+03,0.004255,0.000749,0.003830,1.554449,3.371363e+01,1.590088e-01
h148_10,13.800797,1.353274e+08,1.139460e+09,1.055766e+10,46.469675,-24.02,-133.76,-5.92,136.03,0.022669,NaN,4.378722e+08,1.161519e+02,0.013847,0.035053,0.006264,0.538852,8.833165e-01,7.106595e-03
h148_12,13.800797,1.043767e+08,7.503453e+06,9.071870e+09,43.979036,42.64,281.50,-2.79,284.73,0.000137,NaN,3.043587e+05,8.613388e+01,0.000929,0.001414,0.001445,0.052891,1.522334e-02,2.284602e-02
h148_27,13.800797,8.415728e+07,1.026774e+08,3.249352e+09,31.367917,237.78,147.66,-94.98,295.57,0.000535,NaN,2.159628e+07,2.503571e+01,0.005458,0.006517,0.008144,0.123195,2.343291e-01,1.178148e-03
h148_34,13.800797,5.759679e+06,5.869542e+07,2.628660e+09,29.130301,-296.06,-315.65,-241.34,495.51,0.000000,NaN,6.332316e+06,1.688300e+02,0.000690,0.000282,0.000417,0.556970,1.586624e+00,1.552734e-01
h148_38,13.800797,1.374093e+07,0.000000e+00,1.883522e+09,26.060232,2.87,48.18,-181.80,188.10,0.000000,NaN,0.000000e+00,0.000000e+00,0.000981,0.000951,0.001479,0.000000,0.000000e+00,0.000000e+00
h148_55,13.800797,2.822993e+06,5.263210e+06,1.361924e+09,23.525588,-71.52,14.26,33.44,80.23,0.000000,NaN,1.317506e+06,0.000000e+00,0.001582,0.001107,0.002223,0.021787,8.419661e-02,0.000000e+00
h148_65,13.800797,3.001293e+07,0.000000e+00,8.996108e+08,20.341280,-33.33,-76.81,83.05,117.92,0.000000,NaN,0.000000e+00,0.000000e+00,0.000499,0.000794,0.000972,0.000000,0.000000e+00,0.000000e+00
h148_251,13.800797,2.149496e+06,0.000000e+00,1.815621e+08,11.952184,197.98,6.38,-219.66,295.78,0.000000,NaN,0.000000e+00,0.000000e+00,0.000280,0.000673,0.000846,0.000000,0.000000e+00,0.000000e+00
h148_249,13.800797,2.063790e+06,0.000000e+00,1.861386e+08,12.084551,29.14,180.63,10.97,183.29,0.000000,NaN,0.000000e+00,0.000000e+00,0.000692,0.001447,0.001075,0.000000,0.000000e+00,0.000000e+00
h148_282,13.800797,3.984286e+06,0.000000e+00,1.495318e+08,11.235650,112.71,128.88,60.19,181.49,0.000000,NaN,0.000000e+00,0.000000e+00,0.000207,0.000477,0.000522,0.000000,0.000000e+00,0.000000e+00
h229_14,13.800797,3.338275e+06,2.703543e+07,2.403511e+09,28.258460,257.66,301.63,-53.13,400.24,0.000000,NaN,2.421080e+06,9.500366e+01,0.000651,0.000245,0.000971,0.539821,5.312464e-01,6.970784e-02
h229_18,13.800797,7.714878e+07,0.000000e+00,1.509991e+09,24.209733,20.23,43.32,128.95,137.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.003526,0.005233,0.004190,0.000000,0.000000e+00,0.000000e+00
h229_20,13.800797,8.610682e+05,6.519790e+05,2.025912e+09,26.697664,-7.16,200.96,-183.88,272.48,0.000000,NaN,6.455090e+02,1.334474e+00,0.000332,0.000075,0.000387,0.025534,4.622822e-04,2.459367e-03
h229_22,13.800797,4.786508e+06,0.000000e+00,1.551642e+09,24.447656,-27.96,-38.13,-219.32,224.36,0.000000,NaN,0.000000e+00,0.000000e+00,0.000404,0.000250,0.000646,0.000000,0.000000e+00,0.000000e+00
h229_49,13.800797,6.790767e+06,0.000000e+00,7.641975e+08,19.306726,7.39,-109.24,-11.25,110.06,0.000000,NaN,0.000000e+00,0.000000e+00,0.000750,0.000637,0.000524,0.000000,0.000000e+00,0.000000e+00
h242_8,13.800797,0.000000e+00,2.916159e+05,5.397006e+12,2524.255371,2618.05,-5147.36,-1756.73,6036.19,0.034354,NaN,1.008922e-02,2.359862e-10,0.042365,0.053616,0.033327,0.000075,8.700136e-12,6.126794e-15
h242_10,13.800797,2.477138e+08,2.276692e+09,1.211725e+11,14901.587088,578.01,-945.70,-335.24,1157.94,0.009396,NaN,2.710142e+08,4.157601e+04,0.046579,0.056213,0.045138,0.533666,2.229021e-01,7.969718e-01
h242_21,13.800797,0.000000e+00,0.000000e+00,1.139806e+12,29062.027289,-4040.41,2166.01,6379.09,7855.53,0.000000,NaN,0.000000e+00,0.000000e+00,0.002215,0.000304,0.004424,0.000000,0.000000e+00,0.000000e+00
h242_30,13.800797,5.322599e+07,1.453714e+09,7.091480e+09,24867.343522,-20494.08,-13965.20,-1154.72,24826.75,0.000000,NaN,7.356529e+08,6.335230e-04,0.000724,0.000923,0.000627,21.916692,3.685118e+01,8.742064e-07
h242_38,13.800797,0.000000e+00,0.000000e+00,7.776950e+09,17343.015297,-4648.07,-17372.41,-2285.26,18128.09,0.000000,NaN,0.000000e+00,0.000000e+00,0.000466,0.000075,0.000423,0.000000,0.000000e+00,0.000000e+00
h242_69,13.800797,1.149230e+07,4.381391e+07,9.322223e+09,23912.836453,-5233.07,-18227.97,15780.35,24671.10,0.000000,NaN,6.489503e+06,9.188295e+02,0.002812,0.002372,0.002153,0.170138,1.264801e-01,3.691732e-01
h242_401,13.800797,0.000000e+00,0.000000e+00,8.967824e+10,32993.649324,2363.01,-11798.80,2783.86,12350.93,0.000000,NaN,0.000000e+00,0.000000e+00,0.000509,0.000661,0.000422,0.000000,0.000000e+00,0.000000e+00
h329_7,13.800797,2.747402e+07,2.476791e+08,5.129210e+09,32.738173,53.53,-33.41,15.58,64.99,0.001193,NaN,6.756492e+07,4.063190e-02,0.017682,0.111979,0.002594,0.524004,9.712702e-01,2.060643e-05
h329_29,13.800797,1.491121e+06,0.000000e+00,1.403478e+09,23.658594,-240.56,-506.82,113.85,572.45,0.000000,NaN,0.000000e+00,0.000000e+00,0.001573,0.001954,0.001923,0.000000,0.000000e+00,0.000000e+00
h329_117,13.800797,3.084173e+06,0.000000e+00,2.398850e+08,13.075619,52.26,59.03,-81.65,113.50,0.000000,NaN,0.000000e+00,0.000000e+00,0.000062,0.000077,0.000078,0.000000,0.000000e+00,0.000000e+00

In [17]:
sim_filepath = simulations['filepath']['Elena']

#load and set the units for the simulation
s = pynbody.load(sim_filepath)
s.physical_units() #  and ensure the units are correct
h = s.halos(halo_numbers='v1')

In [23]:
h[1].properties['pos']

SimArray([[ 1929.34069776, -4346.09018251,  1386.55435289],
          [ 1924.18936633, -4344.56504866,  1387.47496525],
          [ 1898.94344651, -4352.04990192,  1462.40172902],
          ...,
          [ 1877.10002058, -4442.10134431,  1476.1066995 ],
          [ 1876.37303018, -4441.91247209,  1476.94312031],
          [ 1877.12479376, -4441.75824507,  1476.53203452]],
         shape=(32638998, 3), 'kpc')

In [24]:
ions.calculate_gas_mass(s)

In [24]:
h[7].mean_by_mass('pos')

SimArray([ 53.90405548, -34.2847789 ,  15.94553042], 'kpc')

In [18]:
pynbody.analysis.halo.center(h[7], return_cen = True)

SimArray([ 53.52581653, -33.40925164,  15.57995842], 'kpc')

In [97]:
h[7].properties['Mvir']/1e9

np.float64(3.47607)

In [101]:
with pynbody.analysis.center(h[7]):
    print(np.max(h[7]['r']))

32.7381727217724

In [110]:
(np.max(h[7]['x']) - np.min(h[7]['x']))/2

SimArray(32.22719087, 'kpc')

In [12]:
pynbody.analysis.halo.center(h[7], return_cen = True).tolist()

[53.525816532036295, -33.409251635239954, 15.57995841779238]

In [88]:
sHaloChars.to_csv(data_name)

In [44]:
pynbody.analysis.angmom.sideon(s)

In [56]:
h[1].physical_units()

In [122]:
s, h1, h = base.load_in_sim("Elena", return_h = True)

In [125]:
subsims = tracking.find_halo_particles(h1, simulations, 'Elena', groupSmalls = False  )##returns a dictionary of subsims for all halos in the simulations,

In [127]:
len(subsims['halos'])

19821

In [128]:
len(subsims['halos'].g)

19821